CREATE SCHEMA IF NOT EXISTS G3_GESTOR_VENTAS;
USE G3_GESTOR_VENTAS;

DROP SCHEMA G3_GESTOR_VENTAS;

-- Ya han sido rellenados
SELECT * FROM VENTAS;
SELECT * FROM DETALLE_VENTAS;
SELECT * FROM PAGOS;

-- Rellenados con datos de prueba
SELECT * FROM CATEGORIAS;
SELECT * FROM CLIENTES;
SELECT * FROM METODO_PAGO;
SELECT * FROM PRODUCTOS;
SELECT * FROM PROVEEDORES;
SELECT * FROM TIPOCLIENTE;
SELECT * FROM TIPOUSUARIO;

-- Agregado despues de insertar el avatar
SELECT * FROM USUARIOS;

-- Insertado desde la app
-- AppDbConnect [https://github.com/LavenderEdit/AppDbConnect.git]
SELECT * FROM AVATARUSUARIO;
